# Generated by Django 5.0.6 on 2024-07-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cart_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='toShow',
            field=models.BooleanField(default=True),
        ),
    ]
